### ISSUE TITLE
FSafeTypes are just a minor inconvenience for people writing external cheats.

### ISSUE THREAD

**Issue by Fischsalat** [BrUnOXaVIeRLeiTE/SCUE5-Plugin#4]
FSafeTypes might be effective to counter people using cheatengine to find values but they are barely an inconvenience for anyone with an SDK.

For clarification, all UStructs and UClasses (including their reflected member functiosn and variables [U/FProperties]), as well as UEnums can be dumped from game memory and recreated basically 1:1. All of these structs and classes from the SDK can be used as if a modder (or cheater) were normally using UnrealEngine. This basically means people can just call the get-/set-functions for FSafeTypes you provided in your `USCLibrary`for blueprint usage, when the mod/cheat is injected into the UE game.
For external mods/cheats (outside of the game process) these unsafe types are just a minor inconvenience as they can be reverse-engineered pretty easily with information obtained from the SDK or placed in the executable by Unreal Engine.

If you really seek to stop people from cheating, or at least make it harder, you should find ways to hinder them from dumping an SDK or making it more difficult for them.

`FSafeBool` from this source:
![image](https://github.com/user-attachments/assets/7a6932c8-69e8-44c5-a159-53f281016c58)

`FSafeBool` in the SDK generated for BeastsOfBermuda (had that SDK laying around, just a random example).
![image](https://github.com/user-attachments/assets/bf90c15d-bb1f-4b16-bf33-991f5c360819)
\
\
`USCLibrary` in this source:
![image](https://github.com/user-attachments/assets/995e85ce-6415-44c6-9d5d-7e3c64d9a959)

`USCLibrary` in the SDK:
![image](https://github.com/user-attachments/assets/990e70aa-098b-4c3c-9be7-9cbb71e138e2)
\
Full SDK for reference (random game using your counter cheating measure):
[Uploading 4.26.0-0+++UE4+Release-4.26-BeastsOfBermuda.zip…]()
\
This being said I hope you have a great day!

**Comment by BrUnOXaVIeRLeiTE** [comment]
That is no secret at all.
